version: '2'

volumes:
  home-dir: {}
  host-keys: {}

services:
  dev:
    environment:
      # list of github usernames whose SSH public keys to
      # install for root user
      GITHUB_USERS_TO_ALLOW_SSH: 'user1 user2'

    volumes:
      - 'home-dir:/root'
      - 'host-keys:/etc/ssh/ssh_host_keys'
