dev:
  # image: quay.io/goodguide/dev:v3
  build: .

  container_name: dev

  extra_hosts:
    - 'docker.dev:172.17.0.1'

  privileged: true # not at all necessary, just might be helpful

  ports:
    - '2222:22' # sshd
    - '60001:60001/udp' # mosh server

  restart: always

  pid: host

  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock' # mount docker socket into container so you can do things like run docker-compose from projects you're working on
    - '/code:/code' # somewhere to put the shit you're working on (if ever using docker, makes it easier if the path inside the container matches the path on the host)

  hostname: 'dev-container'
