version: '2'

services:
  dev:
    image: namick/dockerdev
    extra_hosts:
      - 'docker.dev:172.17.0.1'

    privileged: true # not at all necessary, just might be helpful

    ports:
      - '2222:22' # sshd to the outside world

    restart: always

    pid: host

    volumes:
      # mount docker socket into container so you can do things like run
      # docker-compose from projects you're working on
      - '/var/run/docker.sock:/var/run/docker.sock'

      # somewhere to put the shit you're working on (if ever using docker,
      # makes it easier if the path inside the container matches the path on the host)
      - '/code:/code'

    hostname: 'dev'
